name: Backend CI
on:
  push:
    branches: [ main, ci-cd ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: read

jobs:
  build-test-sonar:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    env:
      
      JWT_SECRET: 0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef

      
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
      SONAR_ORG: ${{ secrets.SONAR_ORG }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      
      - name: Build & Unit tests (JaCoCo XML)
        run: mvn -B -DskipITs verify jacoco:report

      - name: SonarCloud Scan (optional)
        if: ${{ env.SONAR_TOKEN != '' && env.SONAR_PROJECT_KEY != '' && env.SONAR_ORG != '' }}
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: backend
          args: >
            -Dsonar.organization=${{ env.SONAR_ORG }}
            -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }}
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
        env:
          SONAR_TOKEN: ${{ env.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Package (skip tests)
        run: mvn -B -DskipTests package

      - name: Upload JaCoCo HTML (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-html
          path: backend/target/site/jacoco/**
